package cn.dmdl.stl.hospitalbudget.budget.entity;

// Generated 2017-3-8 15:38:50 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * GenericProject generated by hbm2java
 */
@Entity
@Table(name = "generic_project", catalog = "hospital_budget")
public class GenericProject implements java.io.Serializable {

	private Integer theId;
	private Integer thePid;
	private String theValue;
	private Integer projectType;
	private Integer departmentInfoId;
	private Integer fundsSourceId;
	private Double budgetAmount;
	private String theDescription;
	private Integer theState;
	private Date insertTime;
	private Integer insertUser;
	private Date updateTime;
	private Integer updateUser;
	private boolean deleted;

	public GenericProject() {
	}

	public GenericProject(String theValue, boolean deleted) {
		this.theValue = theValue;
		this.deleted = deleted;
	}

	public GenericProject(Integer thePid, String theValue, Integer projectType, Integer departmentInfoId, Integer fundsSourceId, Double budgetAmount, String theDescription, Integer theState, Date insertTime, Integer insertUser, Date updateTime, Integer updateUser, boolean deleted) {
		this.thePid = thePid;
		this.theValue = theValue;
		this.projectType = projectType;
		this.departmentInfoId = departmentInfoId;
		this.fundsSourceId = fundsSourceId;
		this.budgetAmount = budgetAmount;
		this.theDescription = theDescription;
		this.theState = theState;
		this.insertTime = insertTime;
		this.insertUser = insertUser;
		this.updateTime = updateTime;
		this.updateUser = updateUser;
		this.deleted = deleted;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "the_id", unique = true, nullable = false)
	public Integer getTheId() {
		return this.theId;
	}

	public void setTheId(Integer theId) {
		this.theId = theId;
	}

	@Column(name = "the_pid")
	public Integer getThePid() {
		return this.thePid;
	}

	public void setThePid(Integer thePid) {
		this.thePid = thePid;
	}

	@Column(name = "the_value", nullable = false)
	@NotNull
	public String getTheValue() {
		return this.theValue;
	}

	public void setTheValue(String theValue) {
		this.theValue = theValue;
	}

	@Column(name = "project_type")
	public Integer getProjectType() {
		return this.projectType;
	}

	public void setProjectType(Integer projectType) {
		this.projectType = projectType;
	}

	@Column(name = "department_info_id")
	public Integer getDepartmentInfoId() {
		return this.departmentInfoId;
	}

	public void setDepartmentInfoId(Integer departmentInfoId) {
		this.departmentInfoId = departmentInfoId;
	}

	@Column(name = "funds_source_id")
	public Integer getFundsSourceId() {
		return this.fundsSourceId;
	}

	public void setFundsSourceId(Integer fundsSourceId) {
		this.fundsSourceId = fundsSourceId;
	}

	@Column(name = "budget_amount", precision = 22, scale = 0)
	public Double getBudgetAmount() {
		return this.budgetAmount;
	}

	public void setBudgetAmount(Double budgetAmount) {
		this.budgetAmount = budgetAmount;
	}

	@Column(name = "the_description", length = 1024)
	@Length(max = 1024)
	public String getTheDescription() {
		return this.theDescription;
	}

	public void setTheDescription(String theDescription) {
		this.theDescription = theDescription;
	}

	@Column(name = "the_state")
	public Integer getTheState() {
		return this.theState;
	}

	public void setTheState(Integer theState) {
		this.theState = theState;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "insert_time", length = 19)
	public Date getInsertTime() {
		return this.insertTime;
	}

	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}

	@Column(name = "insert_user")
	public Integer getInsertUser() {
		return this.insertUser;
	}

	public void setInsertUser(Integer insertUser) {
		this.insertUser = insertUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "update_user")
	public Integer getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(Integer updateUser) {
		this.updateUser = updateUser;
	}

	@Column(name = "deleted", nullable = false)
	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

}
