package cn.dmdl.stl.hospitalbudget.budget.entity;

// Generated 2017-3-8 15:38:50 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GenericProjectCompiler generated by hbm2java
 */
@Entity
@Table(name = "generic_project_compiler", catalog = "hospital_budget")
public class GenericProjectCompiler implements java.io.Serializable {

	private Integer theId;
	private int projectId;
	private int userInfoId;

	public GenericProjectCompiler() {
	}

	public GenericProjectCompiler(int projectId, int userInfoId) {
		this.projectId = projectId;
		this.userInfoId = userInfoId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "the_id", unique = true, nullable = false)
	public Integer getTheId() {
		return this.theId;
	}

	public void setTheId(Integer theId) {
		this.theId = theId;
	}

	@Column(name = "project_id", nullable = false)
	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	@Column(name = "user_info_id", nullable = false)
	public int getUserInfoId() {
		return this.userInfoId;
	}

	public void setUserInfoId(int userInfoId) {
		this.userInfoId = userInfoId;
	}

}
