package cn.dmdl.stl.hospitalbudget.budget.entity;

// Generated 2017-1-14 18:50:08 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * NormalBudgetIncomeInfo generated by hbm2java
 */
@Entity
@Table(name = "normal_budget_income_info", catalog = "hospital_budget")
public class NormalBudgetIncomeInfo implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer normalBudgetYearId;
	private int deptId;
	private String year;
	private Integer normalProjectId;
	private Integer subProjectId;
	private int projectSource;
	private double budgetAmount;
	private int insertUser;
	private Date insertTime;
	private int confirmFlag;

	public NormalBudgetIncomeInfo() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "normal_budget_year_id", unique = true, nullable = false)
	public Integer getNormalBudgetYearId() {
		return this.normalBudgetYearId;
	}

	public void setNormalBudgetYearId(Integer normalBudgetYearId) {
		this.normalBudgetYearId = normalBudgetYearId;
	}

	@Column(name = "dept_id", nullable = false)
	public int getDeptId() {
		return this.deptId;
	}

	public void setDeptId(int deptId) {
		this.deptId = deptId;
	}

	@Column(name = "year", nullable = false, length = 45)
	@NotNull
	@Length(max = 45)
	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	@Column(name = "normal_project_id")
	public Integer getNormalProjectId() {
		return this.normalProjectId;
	}

	public void setNormalProjectId(Integer normalProjectId) {
		this.normalProjectId = normalProjectId;
	}

	@Column(name = "sub_project_id")
	public Integer getSubProjectId() {
		return this.subProjectId;
	}

	public void setSubProjectId(Integer subProjectId) {
		this.subProjectId = subProjectId;
	}

	@Column(name = "project_source", nullable = false)
	public int getProjectSource() {
		return this.projectSource;
	}

	public void setProjectSource(int projectSource) {
		this.projectSource = projectSource;
	}

	@Column(name = "budget_amount", nullable = false, precision = 22, scale = 0)
	public double getBudgetAmount() {
		return this.budgetAmount;
	}

	public void setBudgetAmount(double budgetAmount) {
		this.budgetAmount = budgetAmount;
	}

	@Column(name = "insert_user", nullable = false)
	public int getInsertUser() {
		return this.insertUser;
	}

	public void setInsertUser(int insertUser) {
		this.insertUser = insertUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "insert_time", nullable = false, length = 19)
	@NotNull
	public Date getInsertTime() {
		return this.insertTime;
	}

	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}

	@Column(name = "confirm_flag", nullable = false)
	public int getConfirmFlag() {
		return this.confirmFlag;
	}

	public void setConfirmFlag(int confirmFlag) {
		this.confirmFlag = confirmFlag;
	}

}
