package cn.dmdl.stl.hospitalbudget.budget.entity;

// Generated 2016-12-27 19:46:56 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

import cn.dmdl.stl.hospitalbudget.hospital.entity.YsDepartmentInfo;

/**
 * ProcessInfo generated by hbm2java
 */
@Entity
@Table(name = "process_info", catalog = "hospital_budget")
public class ProcessInfo implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer processInfoId;
	private String processName;
	private int processType;
	private YsDepartmentInfo ysDepartmentInfo;
	private Date insertTime;
	private int insertUser;
	private Date updateTime;
	private Integer updateUser;
	private boolean deleted;

	public ProcessInfo() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "process_info_id", unique = true, nullable = false)
	public Integer getProcessInfoId() {
		return this.processInfoId;
	}

	public void setProcessInfoId(Integer processInfoId) {
		this.processInfoId = processInfoId;
	}

	@Column(name = "process_name", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getProcessName() {
		return this.processName;
	}

	public void setProcessName(String processName) {
		this.processName = processName;
	}

	@Column(name = "process_type", nullable = false)
	public int getProcessType() {
		return this.processType;
	}

	public void setProcessType(int processType) {
		this.processType = processType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dept_id")
	public YsDepartmentInfo getYsDepartmentInfo() {
		return ysDepartmentInfo;
	}

	public void setYsDepartmentInfo(YsDepartmentInfo ysDepartmentInfo) {
		this.ysDepartmentInfo = ysDepartmentInfo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "insert_time", nullable = false, length = 19)
	@NotNull
	public Date getInsertTime() {
		return this.insertTime;
	}

	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}

	@Column(name = "insert_user", nullable = false)
	public int getInsertUser() {
		return this.insertUser;
	}

	public void setInsertUser(int insertUser) {
		this.insertUser = insertUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "update_user")
	public Integer getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(Integer updateUser) {
		this.updateUser = updateUser;
	}

	@Column(name = "deleted", nullable = false)
	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

}
