package cn.dmdl.stl.hospitalbudget.budget.entity;

// Generated 2016-12-27 19:46:56 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProcessStepUser generated by hbm2java
 */
@Entity
@Table(name = "process_step_user", catalog = "hospital_budget")
public class ProcessStepUser implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer processStepUserId;
	private int processStepInfoId;
	private int userId;
	private int type;

	public ProcessStepUser() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "process_step_user_id", unique = true, nullable = false)
	public Integer getProcessStepUserId() {
		return this.processStepUserId;
	}

	public void setProcessStepUserId(Integer processStepUserId) {
		this.processStepUserId = processStepUserId;
	}

	@Column(name = "process_step_info_id", nullable = false)
	public int getProcessStepInfoId() {
		return this.processStepInfoId;
	}

	public void setProcessStepInfoId(int processStepInfoId) {
		this.processStepInfoId = processStepInfoId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "type", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

}
