package cn.dmdl.stl.hospitalbudget.budget.entity;

// Generated 2016-12-27 19:46:56 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * ProcessStepInfo generated by hbm2java
 */
@Entity
@Table(name = "process_step_info", catalog = "hospital_budget")
public class ProcessStepInfo implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer processStepInfoId;
	private String stepName;
	private ProcessInfo processInfo;
	private int stepIndex;

	public ProcessStepInfo() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "process_step_info_id", unique = true, nullable = false)
	public Integer getProcessStepInfoId() {
		return this.processStepInfoId;
	}

	public void setProcessStepInfoId(Integer processStepInfoId) {
		this.processStepInfoId = processStepInfoId;
	}

	@Column(name = "step_name", nullable = false, length = 45)
	@NotNull
	@Length(max = 45)
	public String getStepName() {
		return this.stepName;
	}

	public void setStepName(String stepName) {
		this.stepName = stepName;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "process_info_id")
	public ProcessInfo getProcessInfo() {
		return processInfo;
	}

	public void setProcessInfo(ProcessInfo processInfo) {
		this.processInfo = processInfo;
	}

	@Column(name = "step_index", nullable = false)
	public int getStepIndex() {
		return this.stepIndex;
	}

	public void setStepIndex(int stepIndex) {
		this.stepIndex = stepIndex;
	}

}
