package cn.dmdl.stl.hospitalbudget.budget.entity;

// Generated 2017-3-7 16:43:45 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RoutineProjectExecutor generated by hbm2java
 */
@Entity
@Table(name = "routine_project_executor", catalog = "hospital_budget")
public class RoutineProjectExecutor implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer theId;
	private int projectId;
	private int userInfoId;

	public RoutineProjectExecutor() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "the_id", unique = true, nullable = false)
	public Integer getTheId() {
		return this.theId;
	}

	public void setTheId(Integer theId) {
		this.theId = theId;
	}

	@Column(name = "project_id", nullable = false)
	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	@Column(name = "user_info_id", nullable = false)
	public int getUserInfoId() {
		return this.userInfoId;
	}

	public void setUserInfoId(int userInfoId) {
		this.userInfoId = userInfoId;
	}

}
