package cn.dmdl.stl.hospitalbudget.budget.entity;

// Generated 2017-1-5 18:04:01 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * TaskOrder generated by hbm2java
 */
@Entity
@Table(name = "task_order", catalog = "hospital_budget")
public class TaskOrder implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer taskOrderId;
	private String orderSn;
	private String taskName;
	private int deptId;
	private int editUserId;
	private int taskType;
	private Date insertTime;
	private int insertUser;
	private int orderStatus;
	private String auditOpinion;
	private int processStepInfoId;

	public TaskOrder() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "task_order_id", unique = true, nullable = false)
	public Integer getTaskOrderId() {
		return this.taskOrderId;
	}

	public void setTaskOrderId(Integer taskOrderId) {
		this.taskOrderId = taskOrderId;
	}

	@Column(name = "order_sn", nullable = false, length = 45)
	@NotNull
	@Length(max = 45)
	public String getOrderSn() {
		return this.orderSn;
	}

	public void setOrderSn(String orderSn) {
		this.orderSn = orderSn;
	}

	@Column(name = "task_name", nullable = false, length = 45)
	@NotNull
	@Length(max = 45)
	public String getTaskName() {
		return this.taskName;
	}

	public void setTaskName(String taskName) {
		this.taskName = taskName;
	}

	@Column(name = "dept_id", nullable = false)
	public int getDeptId() {
		return this.deptId;
	}

	public void setDeptId(int deptId) {
		this.deptId = deptId;
	}

	@Column(name = "edit_user_id", nullable = false)
	public int getEditUserId() {
		return this.editUserId;
	}

	public void setEditUserId(int editUserId) {
		this.editUserId = editUserId;
	}

	@Column(name = "task_type", nullable = false)
	public int getTaskType() {
		return this.taskType;
	}

	public void setTaskType(int taskType) {
		this.taskType = taskType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "insert_time", nullable = false, length = 19)
	@NotNull
	public Date getInsertTime() {
		return this.insertTime;
	}

	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}

	@Column(name = "insert_user", nullable = false)
	public int getInsertUser() {
		return this.insertUser;
	}

	public void setInsertUser(int insertUser) {
		this.insertUser = insertUser;
	}

	@Column(name = "order_status", nullable = false)
	public int getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(int orderStatus) {
		this.orderStatus = orderStatus;
	}

	@Column(name = "audit_opinion", length = 100)
	@Length(max = 100)
	public String getAuditOpinion() {
		return this.auditOpinion;
	}

	public void setAuditOpinion(String auditOpinion) {
		this.auditOpinion = auditOpinion;
	}

	@Column(name = "process_step_info_id", nullable = false)
	public int getProcessStepInfoId() {
		return this.processStepInfoId;
	}

	public void setProcessStepInfoId(int processStepInfoId) {
		this.processStepInfoId = processStepInfoId;
	}

}
