package cn.dmdl.stl.hospitalbudget.budget.entity;

// Generated 2017-1-5 18:04:01 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TaskUser generated by hbm2java
 */
@Entity
@Table(name = "task_user", catalog = "hospital_budget")
public class TaskUser implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer taskUserId;
	private int taskOrderId;
	private int userId;
	private boolean handleFlg;

	public TaskUser() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "task_user_id", unique = true, nullable = false)
	public Integer getTaskUserId() {
		return this.taskUserId;
	}

	public void setTaskUserId(Integer taskUserId) {
		this.taskUserId = taskUserId;
	}

	@Column(name = "task_order_id", nullable = false)
	public int getTaskOrderId() {
		return this.taskOrderId;
	}

	public void setTaskOrderId(int taskOrderId) {
		this.taskOrderId = taskOrderId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "handle_flg", nullable = false)
	public boolean isHandleFlg() {
		return this.handleFlg;
	}

	public void setHandleFlg(boolean handleFlg) {
		this.handleFlg = handleFlg;
	}

}
