package cn.dmdl.stl.hospitalbudget.budget.entity;

// Generated 2017-3-2 18:36:51 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UsualProjectExecutor generated by hbm2java
 */
@Entity
@Table(name = "usual_project_executor", catalog = "hospital_budget")
public class UsualProjectExecutor implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer theId;
	private int usualProjectId;
	private int userInfoId;

	public UsualProjectExecutor() {
	}

	public UsualProjectExecutor(int usualProjectId, int userInfoId) {
		this.usualProjectId = usualProjectId;
		this.userInfoId = userInfoId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "the_id", unique = true, nullable = false)
	public Integer getTheId() {
		return this.theId;
	}

	public void setTheId(Integer theId) {
		this.theId = theId;
	}

	@Column(name = "usual_project_id", nullable = false)
	public int getUsualProjectId() {
		return this.usualProjectId;
	}

	public void setUsualProjectId(int usualProjectId) {
		this.usualProjectId = usualProjectId;
	}

	@Column(name = "user_info_id", nullable = false)
	public int getUserInfoId() {
		return this.userInfoId;
	}

	public void setUserInfoId(int userInfoId) {
		this.userInfoId = userInfoId;
	}

}
