package cn.dmdl.stl.hospitalbudget.budget.entity;

// Generated 2017-3-20 16:17:32 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * YsBudgetCollectionDept generated by hbm2java
 */
@Entity
@Table(name = "ys_budget_collection_dept", catalog = "hospital_budget")
public class YsBudgetCollectionDept implements java.io.Serializable {

	private Integer budgetCollectionDeptId;
	private int deptId;
	private int budgetType;
	private String year;
	private int status;

	public YsBudgetCollectionDept() {
	}

	public YsBudgetCollectionDept(int deptId, int budgetType, String year,
			int status) {
		this.deptId = deptId;
		this.budgetType = budgetType;
		this.year = year;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "budget_collection_dept_id", unique = true, nullable = false)
	public Integer getBudgetCollectionDeptId() {
		return this.budgetCollectionDeptId;
	}

	public void setBudgetCollectionDeptId(Integer budgetCollectionDeptId) {
		this.budgetCollectionDeptId = budgetCollectionDeptId;
	}

	@Column(name = "dept_id", nullable = false)
	public int getDeptId() {
		return this.deptId;
	}

	public void setDeptId(int deptId) {
		this.deptId = deptId;
	}

	@Column(name = "budget_type", nullable = false)
	public int getBudgetType() {
		return this.budgetType;
	}

	public void setBudgetType(int budgetType) {
		this.budgetType = budgetType;
	}

	@Column(name = "year", nullable = false, length = 45)
	@NotNull
	@Length(max = 45)
	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
