package cn.dmdl.stl.hospitalbudget.hospital.entity;

// Generated 2016-12-25 19:33:34 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * YsConventionProjectUser generated by hbm2java
 */
@Entity
@Table(name = "ys_convention_project_user", catalog = "hospital_budget")
public class YsConventionProjectUser implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer theId;
	private int conventionProjectId;
	private int userInfoId;

	public YsConventionProjectUser() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "the_id", unique = true, nullable = false)
	public Integer getTheId() {
		return this.theId;
	}

	public void setTheId(Integer theId) {
		this.theId = theId;
	}

	@Column(name = "convention_project_id", nullable = false)
	public int getConventionProjectId() {
		return this.conventionProjectId;
	}

	public void setConventionProjectId(int conventionProjectId) {
		this.conventionProjectId = conventionProjectId;
	}

	@Column(name = "user_info_id", nullable = false)
	public int getUserInfoId() {
		return this.userInfoId;
	}

	public void setUserInfoId(int userInfoId) {
		this.userInfoId = userInfoId;
	}

}
