package cn.dmdl.stl.hospitalbudget.hospital.entity;

// Generated 2016-12-28 16:31:33 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.validator.NotNull;

/**
 * YsConventionProjectExtend generated by hbm2java
 */
@Entity
@Table(name = "ys_convention_project_extend", catalog = "hospital_budget")
public class YsConventionProjectExtend implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer theId;
	private YsConventionProject ysConventionProject;
	private String theValue;
	private String theDescription;
	private BigDecimal totalAmount;

	public YsConventionProjectExtend() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "the_id", unique = true, nullable = false)
	public Integer getTheId() {
		return this.theId;
	}

	public void setTheId(Integer theId) {
		this.theId = theId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "convention_project_id")
	public YsConventionProject getYsConventionProject() {
		return ysConventionProject;
	}

	public void setYsConventionProject(YsConventionProject ysConventionProject) {
		this.ysConventionProject = ysConventionProject;
	}

	@Column(name = "the_value", nullable = false)
	@NotNull
	public String getTheValue() {
		return this.theValue;
	}

	public void setTheValue(String theValue) {
		this.theValue = theValue;
	}

	@Column(name = "the_description")
	public String getTheDescription() {
		return this.theDescription;
	}

	public void setTheDescription(String theDescription) {
		this.theDescription = theDescription;
	}

	@Column(name = "total_amount", precision = 65)
	public BigDecimal getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(BigDecimal totalAmount) {
		this.totalAmount = totalAmount;
	}

}
