package cn.dmdl.stl.hospitalbudget.hospital.entity;

// Generated 2016-12-17 14:37:44 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * YsGeneralProjectUser generated by hbm2java
 */
@Entity
@Table(name = "ys_general_project_user", catalog = "hospital_budget")
public class YsGeneralProjectUser implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer theId;
	private int generalProjectId;
	private int userInfoId;

	public YsGeneralProjectUser() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "the_id", unique = true, nullable = false)
	public Integer getTheId() {
		return this.theId;
	}

	public void setTheId(Integer theId) {
		this.theId = theId;
	}

	@Column(name = "general_project_id", nullable = false)
	public int getGeneralProjectId() {
		return this.generalProjectId;
	}

	public void setGeneralProjectId(int generalProjectId) {
		this.generalProjectId = generalProjectId;
	}

	@Column(name = "user_info_id", nullable = false)
	public int getUserInfoId() {
		return this.userInfoId;
	}

	public void setUserInfoId(int userInfoId) {
		this.userInfoId = userInfoId;
	}

}
