package cn.dmdl.stl.hospitalbudget.hospital.entity;

// Generated 2016-11-29 0:18:30 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.validator.NotNull;

/**
 * YsWorkflowConfig generated by hbm2java
 */
@Entity
@Table(name = "ys_workflow_config", catalog = "hospital_budget")
public class YsWorkflowConfig implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer workflowId;
	private String workflowName;
	private String projectTypes;
	private String applicableDepartment;

	public YsWorkflowConfig() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "workflow_id", unique = true, nullable = false)
	public Integer getWorkflowId() {
		return this.workflowId;
	}

	public void setWorkflowId(Integer workflowId) {
		this.workflowId = workflowId;
	}

	@Column(name = "workflow_name", nullable = false)
	@NotNull
	public String getWorkflowName() {
		return this.workflowName;
	}

	public void setWorkflowName(String workflowName) {
		this.workflowName = workflowName;
	}

	@Column(name = "project_types")
	public String getProjectTypes() {
		return this.projectTypes;
	}

	public void setProjectTypes(String projectTypes) {
		this.projectTypes = projectTypes;
	}

	@Column(name = "applicable_department")
	public String getApplicableDepartment() {
		return this.applicableDepartment;
	}

	public void setApplicableDepartment(String applicableDepartment) {
		this.applicableDepartment = applicableDepartment;
	}

}
