package cn.dmdl.stl.hospitalbudget.execute.entity;

// Generated 2017-3-5 14:03:51 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;

/**
 * EarnConfirmProduct generated by hbm2java
 */
@Entity
@Table(name = "earn_confirm_product", catalog = "hospital_budget")
public class EarnConfirmProduct implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -571637315781573946L;
	private Integer earnConfirmProductId;
	private int earnConfirmId;
	private float actualAmount;
	private Float budgetAmountYear; //年预算金额
	private float confirmAmount; //已到账总金额
	private float notConfirmAmount;//未到账时间
	private Date confirmDate;//到账时间
	private String remark;//备注
	private String fileUrl;
	private Integer routineProjectId;
	private Integer genericProjectId;

	public EarnConfirmProduct() {
	}

	public EarnConfirmProduct(int earnConfirmId, float actualAmount, float confirmAmount, float notConfirmAmount) {
		this.earnConfirmId = earnConfirmId;
		this.actualAmount = actualAmount;
		this.confirmAmount = confirmAmount;
		this.notConfirmAmount = notConfirmAmount;
	}

	public EarnConfirmProduct(int earnConfirmId, float actualAmount, Float budgetAmountYear, float confirmAmount, float notConfirmAmount, Date confirmDate, String remark, String fileUrl) {
		this.earnConfirmId = earnConfirmId;
		this.actualAmount = actualAmount;
		this.budgetAmountYear = budgetAmountYear;
		this.confirmAmount = confirmAmount;
		this.notConfirmAmount = notConfirmAmount;
		this.confirmDate = confirmDate;
		this.remark = remark;
		this.fileUrl = fileUrl;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "earn_confirm_product_id", unique = true, nullable = false)
	public Integer getEarnConfirmProductId() {
		return this.earnConfirmProductId;
	}

	public void setEarnConfirmProductId(Integer earnConfirmProductId) {
		this.earnConfirmProductId = earnConfirmProductId;
	}

	@Column(name = "earn_confirm_id", nullable = false)
	public int getEarnConfirmId() {
		return this.earnConfirmId;
	}

	public void setEarnConfirmId(int earnConfirmId) {
		this.earnConfirmId = earnConfirmId;
	}

	@Column(name = "actual_amount", nullable = false, precision = 11)
	public float getActualAmount() {
		return this.actualAmount;
	}

	public void setActualAmount(float actualAmount) {
		this.actualAmount = actualAmount;
	}

	@Column(name = "budget_amount_year", precision = 11)
	public Float getBudgetAmountYear() {
		return this.budgetAmountYear;
	}

	public void setBudgetAmountYear(Float budgetAmountYear) {
		this.budgetAmountYear = budgetAmountYear;
	}

	@Column(name = "confirm_amount", nullable = false, precision = 11)
	public float getConfirmAmount() {
		return this.confirmAmount;
	}

	public void setConfirmAmount(float confirmAmount) {
		this.confirmAmount = confirmAmount;
	}

	@Column(name = "not_confirm_amount", nullable = false, precision = 11)
	public float getNotConfirmAmount() {
		return this.notConfirmAmount;
	}

	public void setNotConfirmAmount(float notConfirmAmount) {
		this.notConfirmAmount = notConfirmAmount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "confirm_date", length = 19)
	public Date getConfirmDate() {
		return this.confirmDate;
	}

	public void setConfirmDate(Date confirmDate) {
		this.confirmDate = confirmDate;
	}

	@Column(name = "remark", length = 500)
	@Length(max = 500)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "file_url", length = 500)
	@Length(max = 500)
	public String getFileUrl() {
		return this.fileUrl;
	}

	public void setFileUrl(String fileUrl) {
		this.fileUrl = fileUrl;
	}
	@Column(name = "routine_project_id")
	public Integer getRoutineProjectId() {
		return routineProjectId;
	}

	public void setRoutineProjectId(Integer routineProjectId) {
		this.routineProjectId = routineProjectId;
	}
	@Column(name = "generic_project_id")
	public Integer getGenericProjectId() {
		return genericProjectId;
	}

	public void setGenericProjectId(Integer genericProjectId) {
		this.genericProjectId = genericProjectId;
	}

}
