package cn.dmdl.stl.hospitalbudget.admin.entity;

// Generated 2016-11-5 23:47:41 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.NotNull;

/**
 * LoginInfo generated by hbm2java
 */
@Entity
@Table(name = "login_info", catalog = "hospital_budget")
public class LoginInfo implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer loginInfoId;
	private int userInfoId;
	private Date loginTime;
	private Date logoutTime;

	public LoginInfo() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "login_info_id", unique = true, nullable = false)
	public Integer getLoginInfoId() {
		return this.loginInfoId;
	}

	public void setLoginInfoId(Integer loginInfoId) {
		this.loginInfoId = loginInfoId;
	}

	@Column(name = "user_info_id", nullable = false)
	public int getUserInfoId() {
		return this.userInfoId;
	}

	public void setUserInfoId(int userInfoId) {
		this.userInfoId = userInfoId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "login_time", nullable = false, length = 19)
	@NotNull
	public Date getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "logout_time", length = 19)
	public Date getLogoutTime() {
		return this.logoutTime;
	}

	public void setLogoutTime(Date logoutTime) {
		this.logoutTime = logoutTime;
	}

}
