package cn.dmdl.stl.hospitalbudget.admin.entity;

// Generated 2016-12-19 22:53:00 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * MenuInfo generated by hbm2java
 */
@Entity
@Table(name = "menu_info", catalog = "hospital_budget")
public class MenuInfo implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer theId;
	private MenuInfo menuInfo;
	private String theValue;
	private String iconSrc;
	private String tabTitle;
	private String tabUrl;
	private String permissionKey;
	private int displayOrder;
	private boolean deleted;

	public MenuInfo() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "the_id", unique = true, nullable = false)
	public Integer getTheId() {
		return this.theId;
	}

	public void setTheId(Integer theId) {
		this.theId = theId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "the_pid")
	public MenuInfo getMenuInfo() {
		return menuInfo;
	}

	public void setMenuInfo(MenuInfo menuInfo) {
		this.menuInfo = menuInfo;
	}

	@Column(name = "the_value", nullable = false)
	@NotNull
	public String getTheValue() {
		return this.theValue;
	}

	public void setTheValue(String theValue) {
		this.theValue = theValue;
	}

	@Column(name = "icon_src", length = 1024)
	@Length(max = 1024)
	public String getIconSrc() {
		return this.iconSrc;
	}

	public void setIconSrc(String iconSrc) {
		this.iconSrc = iconSrc;
	}

	@Column(name = "tab_title")
	public String getTabTitle() {
		return this.tabTitle;
	}

	public void setTabTitle(String tabTitle) {
		this.tabTitle = tabTitle;
	}

	@Column(name = "tab_url", length = 1024)
	@Length(max = 1024)
	public String getTabUrl() {
		return this.tabUrl;
	}

	public void setTabUrl(String tabUrl) {
		this.tabUrl = tabUrl;
	}

	@Column(name = "permission_key")
	public String getPermissionKey() {
		return this.permissionKey;
	}

	public void setPermissionKey(String permissionKey) {
		this.permissionKey = permissionKey;
	}

	@Column(name = "display_order", nullable = false)
	public int getDisplayOrder() {
		return this.displayOrder;
	}

	public void setDisplayOrder(int displayOrder) {
		this.displayOrder = displayOrder;
	}

	@Column(name = "deleted", nullable = false)
	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

}
