package cn.dmdl.stl.hospitalbudget.admin.entity;

// Generated 2016-11-7 23:44:06 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.NotNull;

/**
 * MessageInfo generated by hbm2java
 */
@Entity
@Table(name = "message_info", catalog = "hospital_budget")
public class MessageInfo implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer messageInfoId;
	private String messageName;
	private String messageValue;
	private Date insertTime;
	private Integer insertUser;
	private Date updateTime;
	private Integer updateUser;
	private boolean deleted;

	public MessageInfo() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "message_info_id", unique = true, nullable = false)
	public Integer getMessageInfoId() {
		return this.messageInfoId;
	}

	public void setMessageInfoId(Integer messageInfoId) {
		this.messageInfoId = messageInfoId;
	}

	@Column(name = "message_name", nullable = false)
	@NotNull
	public String getMessageName() {
		return this.messageName;
	}

	public void setMessageName(String messageName) {
		this.messageName = messageName;
	}

	@Column(name = "message_value", nullable = false)
	@NotNull
	public String getMessageValue() {
		return this.messageValue;
	}

	public void setMessageValue(String messageValue) {
		this.messageValue = messageValue;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "insert_time", length = 19)
	public Date getInsertTime() {
		return this.insertTime;
	}

	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}

	@Column(name = "insert_user")
	public Integer getInsertUser() {
		return this.insertUser;
	}

	public void setInsertUser(Integer insertUser) {
		this.insertUser = insertUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "update_user")
	public Integer getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(Integer updateUser) {
		this.updateUser = updateUser;
	}

	@Column(name = "deleted", nullable = false)
	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

}
