package cn.dmdl.stl.hospitalbudget.admin.entity;

// Generated 2016-10-18 1:21:48 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.NotNull;

/**
 * PermissionInfo generated by hbm2java
 */
@Entity
@Table(name = "permission_info", catalog = "hospital_budget")
public class PermissionInfo implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer permissionInfoId;
	private String permissionName;
	private String abbreviation;
	private String permissionKey;
	private String description;
	private Date insertTime;
	private Integer insertUser;
	private Date updateTime;
	private Integer updateUser;
	private boolean deleted;

	public PermissionInfo() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "permission_info_id", unique = true, nullable = false)
	public Integer getPermissionInfoId() {
		return this.permissionInfoId;
	}

	public void setPermissionInfoId(Integer permissionInfoId) {
		this.permissionInfoId = permissionInfoId;
	}

	@Column(name = "permission_name", nullable = false)
	@NotNull
	public String getPermissionName() {
		return this.permissionName;
	}

	public void setPermissionName(String permissionName) {
		this.permissionName = permissionName;
	}

	@Column(name = "abbreviation")
	public String getAbbreviation() {
		return this.abbreviation;
	}

	public void setAbbreviation(String abbreviation) {
		this.abbreviation = abbreviation;
	}

	@Column(name = "permission_key", nullable = false)
	@NotNull
	public String getPermissionKey() {
		return this.permissionKey;
	}

	public void setPermissionKey(String permissionKey) {
		this.permissionKey = permissionKey;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "insert_time", length = 19)
	public Date getInsertTime() {
		return this.insertTime;
	}

	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}

	@Column(name = "insert_user")
	public Integer getInsertUser() {
		return this.insertUser;
	}

	public void setInsertUser(Integer insertUser) {
		this.insertUser = insertUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "update_user")
	public Integer getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(Integer updateUser) {
		this.updateUser = updateUser;
	}

	@Column(name = "deleted", nullable = false)
	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

}
