package cn.dmdl.stl.hospitalbudget.admin.entity;

// Generated 2017-3-16 11:27:21 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * QuickStart generated by hbm2java
 */
@Entity
@Table(name = "quick_start", catalog = "hospital_budget")
public class QuickStart implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer theId;
	private int userInfoId;
	private int menuInfoId;

	public QuickStart() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "the_id", unique = true, nullable = false)
	public Integer getTheId() {
		return this.theId;
	}

	public void setTheId(Integer theId) {
		this.theId = theId;
	}

	@Column(name = "user_info_id", nullable = false)
	public int getUserInfoId() {
		return this.userInfoId;
	}

	public void setUserInfoId(int userInfoId) {
		this.userInfoId = userInfoId;
	}

	@Column(name = "menu_info_id", nullable = false)
	public int getMenuInfoId() {
		return this.menuInfoId;
	}

	public void setMenuInfoId(int menuInfoId) {
		this.menuInfoId = menuInfoId;
	}

}
