package cn.dmdl.stl.hospitalbudget.admin.entity;

// Generated 2016-10-23 19:59:27 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RolePermission generated by hbm2java
 */
@Entity
@Table(name = "role_permission", catalog = "hospital_budget")
public class RolePermission implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer rolePermissionId;
	private int roleInfoId;
	private int permissionInfoId;

	public RolePermission() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "role_permission_id", unique = true, nullable = false)
	public Integer getRolePermissionId() {
		return this.rolePermissionId;
	}

	public void setRolePermissionId(Integer rolePermissionId) {
		this.rolePermissionId = rolePermissionId;
	}

	@Column(name = "role_info_id", nullable = false)
	public int getRoleInfoId() {
		return this.roleInfoId;
	}

	public void setRoleInfoId(int roleInfoId) {
		this.roleInfoId = roleInfoId;
	}

	@Column(name = "permission_info_id", nullable = false)
	public int getPermissionInfoId() {
		return this.permissionInfoId;
	}

	public void setPermissionInfoId(int permissionInfoId) {
		this.permissionInfoId = permissionInfoId;
	}

}
