package cn.dmdl.stl.hospitalbudget.admin.entity;

// Generated 2016-12-6 17:03:30 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.validator.NotNull;

/**
 * SystemSettings generated by hbm2java
 */
@Entity
@Table(name = "system_settings", catalog = "hospital_budget")
public class SystemSettings implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer theId;
	private String theLabel;
	private String theKey;
	private String theValue;

	public SystemSettings() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "the_id", unique = true, nullable = false)
	public Integer getTheId() {
		return this.theId;
	}

	public void setTheId(Integer theId) {
		this.theId = theId;
	}

	@Column(name = "the_label", nullable = false)
	@NotNull
	public String getTheLabel() {
		return this.theLabel;
	}

	public void setTheLabel(String theLabel) {
		this.theLabel = theLabel;
	}

	@Column(name = "the_key", nullable = false)
	@NotNull
	public String getTheKey() {
		return this.theKey;
	}

	public void setTheKey(String theKey) {
		this.theKey = theKey;
	}

	@Column(name = "the_value", nullable = false)
	@NotNull
	public String getTheValue() {
		return this.theValue;
	}

	public void setTheValue(String theValue) {
		this.theValue = theValue;
	}

}
