package cn.dmdl.stl.hospitalbudget.admin.entity;

// Generated 2017-3-11 18:56:00 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.validator.NotNull;

/**
 * SystemTheme generated by hbm2java
 */
@Entity
@Table(name = "system_theme", catalog = "hospital_budget")
public class SystemTheme implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer theId;
	private String theValue;
	private String cssPath;
	private String theDescription;
	private boolean enabled;

	public SystemTheme() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "the_id", unique = true, nullable = false)
	public Integer getTheId() {
		return this.theId;
	}

	public void setTheId(Integer theId) {
		this.theId = theId;
	}

	@Column(name = "the_value", nullable = false)
	@NotNull
	public String getTheValue() {
		return this.theValue;
	}

	public void setTheValue(String theValue) {
		this.theValue = theValue;
	}

	@Column(name = "css_path", nullable = false)
	@NotNull
	public String getCssPath() {
		return this.cssPath;
	}

	public void setCssPath(String cssPath) {
		this.cssPath = cssPath;
	}

	@Column(name = "the_description")
	public String getTheDescription() {
		return this.theDescription;
	}

	public void setTheDescription(String theDescription) {
		this.theDescription = theDescription;
	}

	@Column(name = "enabled", nullable = false)
	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

}
