package cn.dmdl.stl.hospitalbudget.admin.entity;

// Generated 2016-9-15 0:50:30 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.NotNull;

import cn.dmdl.stl.hospitalbudget.hospital.entity.YsDepartmentInfo;

/**
 * UserInfo generated by hbm2java 用户信息
 */
@Entity
@Table(name = "user_info", catalog = "hospital_budget")
public class UserInfo implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer userInfoId;// PRIMARY KEY
	private UserInfoExtend userInfoExtend;// 用户信息-扩展
	private RoleInfo roleInfo;// 角色信息
	private YsDepartmentInfo ysDepartmentInfo;// 科室信息
	private String username;// 用户名
	private String password;// 密码
	private SystemTheme systemTheme;
	private boolean enabled;// 已启用 0否 1是
	private Date insertTime;// 插入时间
	private Integer insertUser;// 插入用户
	private Date updateTime;// 修改时间
	private Integer updateUser;// 修改用户
	private boolean deleted;// 已删除 0否 1是

	public UserInfo() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_info_id", unique = true, nullable = false)
	public Integer getUserInfoId() {
		return this.userInfoId;
	}

	public void setUserInfoId(Integer userInfoId) {
		this.userInfoId = userInfoId;
	}

	@Column(name = "username", nullable = false)
	@NotNull
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false)
	@NotNull
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "system_theme_id")
	public SystemTheme getSystemTheme() {
		return systemTheme;
	}

	public void setSystemTheme(SystemTheme systemTheme) {
		this.systemTheme = systemTheme;
	}

	@Column(name = "enabled", nullable = false)
	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "insert_time", length = 19)
	public Date getInsertTime() {
		return this.insertTime;
	}

	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}

	@Column(name = "insert_user")
	public Integer getInsertUser() {
		return this.insertUser;
	}

	public void setInsertUser(Integer insertUser) {
		this.insertUser = insertUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "update_user")
	public Integer getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(Integer updateUser) {
		this.updateUser = updateUser;
	}

	@Column(name = "deleted", nullable = false)
	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_info_extend_id", nullable = false)
	public UserInfoExtend getUserInfoExtend() {
		return userInfoExtend;
	}

	public void setUserInfoExtend(UserInfoExtend userInfoExtend) {
		this.userInfoExtend = userInfoExtend;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_info_id", nullable = false)
	public RoleInfo getRoleInfo() {
		return roleInfo;
	}

	public void setRoleInfo(RoleInfo roleInfo) {
		this.roleInfo = roleInfo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "department_info_id")
	public YsDepartmentInfo getYsDepartmentInfo() {
		return ysDepartmentInfo;
	}

	public void setYsDepartmentInfo(YsDepartmentInfo ysDepartmentInfo) {
		this.ysDepartmentInfo = ysDepartmentInfo;
	}

}
